### ISSUE TITLE
NullPointerException PerformExecutor.java:155

### ISSUE THREAD

**Issue by Johnlon** [jenkinsci/coordinator-plugin#38]
My job fails when it is triggered by an SCM change, however runs fine if I hit the build button.

ERROR: Build step failed with exception
java.lang.NullPointerException
    at org.jenkinsci.plugins.coordinator.model.PerformExecutor.prepareExecutionPlan(PerformExecutor.java:155)
    at org.jenkinsci.plugins.coordinator.model.PerformExecutor.execute(PerformExecutor.java:95)
    at org.jenkinsci.plugins.coordinator.model.CoordinatorBuilder.perform(CoordinatorBuilder.java:58)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
    at hudson.model.Build$BuildExecution.build(Build.java:205)
    at hudson.model.Build$BuildExecution.doRun(Build.java:162)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
    at hudson.model.Run.execute(Run.java:1738)
    at hudson.model.Build.run(Build.java:113)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Build step 'Coordinator' marked build as failure
Finished: FAILURE

The CI job is pretty vanilla - 6 parallel steps (names removed for privacy).

![img](https://cloud.githubusercontent.com/assets/836248/16158255/5fdd4c3c-34b4-11e6-8f3c-a095f152b4a5.png)

**Comment by ace-han** [comment]
I need to setup an gitlab hook to see whats going wrong, which is gonna to take a while.

**Comment by Johnlon** [comment]
Thanks - currently my process is do a git checkin then to wait for the build to fail and then restart it manually.

**Comment by Johnlon** [comment]
It may be relevant but I've noticed that my build page suggests the coordinator build job requires parameters? But I can't see how this can be the case as there are none in the job def.

```
This build requires parameters:

Build
-------
Coordinator
  Execution Plan

```

**Comment by Johnlon** [comment]
If I setup a new freestyle build that is set to trigger the coordinator build.
Then manually running the freestyle build causes the coordinator build to fail with ths NPE.
Recall runnign the coord build directly doesn't fail.

Is the problem rooted in the fact that the build is parameterised?
ie parameterised by the coordinator execution plan?

**Comment by ace-han** [comment]
I will take a close look into this during the coming weekend
