### ISSUE TITLE
org.jenkinsci.plugins.coordinator.model.CoordinatorProject$2 is missing its descriptor

### ISSUE THREAD

**Issue by maimas** [jenkinsci/coordinator-plugin#39]
hudson.util.HudsonFailedToLoad: java.lang.AssertionError: class org.jenkinsci.plugins.coordinator.model.CoordinatorProject$2 is missing its descriptor
    at hudson.WebAppMain$3.run(WebAppMain.java:241)
Caused by: java.lang.AssertionError: class org.jenkinsci.plugins.coordinator.model.CoordinatorProject$2 is missing its descriptor
    at jenkins.model.Jenkins.getDescriptorOrDie(Jenkins.java:1304)
    at hudson.model.JobProperty.getDescriptor(JobProperty.java:105)
    at jenkins.model.OptionalJobProperty.getDescriptor(OptionalJobProperty.java:43)
    at jenkins.model.OptionalJobProperty.getDescriptor(OptionalJobProperty.java:39)
    at hudson.model.Descriptor.toMap(Descriptor.java:982)
    at hudson.model.Job.getProperties(Job.java:559)
    at org.jenkinsci.plugins.envinject.migration.EnvInjectMigrationListener.onLoaded(EnvInjectMigrationListener.java:45)
    at jenkins.model.Jenkins.<init>(Jenkins.java:921)
    at hudson.model.Hudson.<init>(Hudson.java:85)
    at hudson.model.Hudson.<init>(Hudson.java:81)
    at hudson.WebAppMain$3.run(WebAppMain.java:227)

**Comment by ace-han** [comment]
Usually reinstall this plugin and restart `Jenkins` will resolve this problem.

We've come to this problem quite a lot during development.

**Comment by maimas** [comment]
Thanks...... It worked but I lost all my jobs that belongs to this plugin.

**Comment by philmadden83** [comment]
Can this be closed?

**Comment by ace-han** [comment]
Close for release 1.3

Please raise it out if this issue constantly hit on you
