### ISSUE TITLE
Null Pointer Exception thrown when build triggered by SCM change

### ISSUE THREAD

**Issue by philmadden83** [jenkinsci/coordinator-plugin#41]
NullPointerExecption thrown when calling prepareExecutionPlan when build is triggered as a result of an SCM change.

Build triggered via the hudson.triggers.SCMTrigger.SCMAction Action.

```java
ERROR: Build step failed with exception
java.lang.NullPointerException
	at org.jenkinsci.plugins.coordinator.model.PerformExecutor.prepareExecutionPlan(PerformExecutor.java:157)
	at org.jenkinsci.plugins.coordinator.model.PerformExecutor.execute(PerformExecutor.java:98)
	at org.jenkinsci.plugins.coordinator.model.CoordinatorBuilder.perform(CoordinatorBuilder.java:58)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.Build.run(Build.java:113)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Build step 'Coordinator' marked build as failure
[BFA] Scanning build for known causes...
[BFA] No failure causes found
```

**Comment by philmadden83** [comment]
I believe this call returns null

https://github.com/jenkinsci/coordinator-plugin/blob/develop/src/main/java/org/jenkinsci/plugins/coordinator/model/CoordinatorBuild.java#L286

**Comment by philmadden83** [comment]
Sames as issue #38
